TWITTER_URLS = [
    "https://x.com/sama",
    "https://x.com/github",
    "https://x.com/gui_penedo",
    "https://x.com/01Ai_Yi",
    "https://x.com/gneubig",
    "https://x.com/AssemblyAI",
    "https://x.com/perplexity_ai",

    "https://x.com/ollama",
    "https://x.com/IterIntellectus",
    "https://x.com/seti_park",
    "https://x.com/FireworksAi_HQ",
    "https://x.com/NVIDIAAIDev",
    "https://x.com/sundarpichai",
    "https://x.com/wunderwuzzi23",

    "https://x.com/cognition_labs",
    "https://x.com/sunjiao123sun_",
    "https://x.com/peteratmsr",
    "https://x.com/GaryMarcus",
    "https://x.com/runwayml",
    "https://x.com/OpenAI",

    "https://x.com/AIatMeta",
    "https://x.com/windsurf_ai",
    "https://x.com/StanfordHAI",
    "https://x.com/omarsar0",
    "https://x.com/AISafetyMemes",
    "https://x.com/MSFTResearch",

    "https://x.com/xenovacom",
    "https://x.com/tydsh",
    "https://x.com/NeurIPsConf",
    "https://x.com/SiliconFlowAI",
    "https://x.com/intern_lm",
    "https://x.com/alexrives",
    "https://x.com/deepseek_ai",

    "https://x.com/DrJimFan",
    "https://x.com/Scobleizer",
    "https://x.com/AndrewYNg",
    "https://x.com/SakanaAILabs",
    "https://x.com/LumaLabsAI",

    "https://x.com/Alibaba_Qwen",
    "https://x.com/mikeknoop",
    "https://x.com/gdb",
    "https://x.com/GoogleAI",
    "https://x.com/OpenAINewsroom",
    "https://x.com/OpenBMB",

    "https://x.com/nvidia",
    "https://x.com/satyanadella",
    "https://x.com/LangChainAi",
    "https://x.com/garrytan",
    "https://x.com/behrouz_ali",

    "https://x.com/kyutai_labs",
    "https://x.com/spacex",
    "https://x.com/rainisto",
    "https://x.com/unusual_whales",
    "https://x.com/patrickc",
    "https://x.com/linoy_tsaban",
    "https://x.com/itsPaulAi",

    "https://x.com/ProfTomYeh",
    "https://x.com/JacquesThibs",
    "https://x.com/alexalbert__",
    "https://x.com/douwekiela",
    "https://x.com/AlecRad",
    "https://x.com/dnystedt",
    "https://x.com/Haojun_Zhao14",
    
    "https://x.com/Teslaconomics",
    "https://x.com/Koven_Yu",
    "https://x.com/code",
    "https://x.com/ClementDelangue",
    "https://x.com/morteymike",
    "https://x.com/_jasonwei",
    "https://x.com/sriramk",
    "https://x.com/sainingxie",

    "https://x.com/hume_ai",
    "https://x.com/_philschmid",
    "https://x.com/TIIuae",
    "https://x.com/midjourney",
    "https://x.com/NVIDIARobotics",
    "https://x.com/OpenAiDevs",

    "https://x.com/TONGYI_SpeechAI",
    "https://x.com/ideogram_ai",
    "https://x.com/UnitreeRobotics",
    "https://x.com/juberti",
    "https://x.com/CerebrasSystems",
    "https://x.com/kimmonismus",
    "https://x.com/rohanpaul_ai",
    "https://x.com/pika_labs",
    "https://x.com/stevenbjohnson",
    "https://x.com/GoogleCloudTech",

    "https://x.com/minchoi",
    "https://x.com/julien_c",
    "https://x.com/mervenoyann",
    "https://x.com/_nateraw",
    "https://x.com/huggingface",
    "https://x.com/tunguz",
    "https://x.com/rasbt",
    "https://x.com/osanseviero",
    "https://x.com/fchollet",
    "https://x.com/mishig25",
    "https://x.com/abhi1thakur",
    "https://x.com/victormustar",
    "https://x.com/Waymo",
    "https://x.com/cursor_ai", 
    "https://x.com/dair_ai",
    "https://x.com/IFLScience",
    "https://x.com/sciam",
    "https://x.com/jed_yang",
    "https://x.com/freddy_alfonso_",
    "https://x.com/emollick",
    "https://x.com/billyuchenlin",
    "https://x.com/vitrupo",
    "https://x.com/EdwardSun0909",
    "https://x.com/Guodaya",
    "https://x.com/ajassy",
    "https://x.com/chetanp",

    "https://x.com/XDevelopers",
]   